# Generated by Django 3.2.8 on 2021-11-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=30)),
                ('nome_cientifico', models.CharField(max_length=30)),
                ('estacao', models.CharField(choices=[('P', 'Primavera'), ('V', 'Verão'), ('O', 'Outono'), ('I', 'Inverno')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='vaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=30)),
                ('tamanho', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Medio'), ('G', 'Grande')], max_length=1)),
            ],
        ),
    ]
